apiVersion: v2
name: hello-world
description: A simple Hello world Flask app
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - flask
  - hello-world
  - example
maintainers:
  - name: Justin Jennings